name: Micros Workflow Deployment

on:
    push:
        branches: [main]

jobs:
    build_and_push:
        name: Build and Push Docker Images
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            
            - name: Extract metadata for Admin
              id: meta
              uses: docker/metadata-action@v4
              with:
                images: ${{ secrets.DOCKER_USERNAME }}/micros_admin
                tags: |
                    type=ref,event=branch
                    type=semver,pattern={{version}}
                    type=sha,format=short
                    latest
            
                    - name: Extract metadata for Fastpi
                    id: meta
                    uses: docker/metadata-action@v4
                    with:
                      images: ${{ secrets.DOCKER_USERNAME }}/micros_fastpi
                      tags: |
                          type=ref,event=branch
                          type=semver,pattern={{version}}
                          type=sha,format=short
                          latest
            
            - name: Build and Push Admin Service
              uses: docker/build-push-action@v4
              with:
                context: ./admin
                push: true
                tags:  ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
                cache-from: type=gha
                cache-to: type=gha,mode=max
            
            - name: Build and Push for Fastpi Service
              uses: docker/build-push-action@v4
              with:
                context: ./fastpi
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
                cache-from: type=gha
                cache-to: type=gha,mode=max