name: Micros Workflow

on:
    pull_request:
        branches: [main]

jobs:
    tests:
        name: Tests
        runs-on: ubuntu-latest

        steps:
            - name: Check out code
              uses: actions/checkout@v4
            
            - name: Set up python
              uses: actions/setup-python@v5
              with:
                python-version: '3.12'
            
            - name: Run tests
              run: |
                pytest fastpi/tests
              